electorAccount = "relay1"
enableApi = true
gasPrice = "0.05ufis"
keystorePath = "./keys/stafihub"
listenAddr = ":8083"
stafiHubEndpointList = ["https://test-rpc1.stafihub.io:443"]

[db]
host = "127.0.0.1" # mysql host ip
name = "station" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username

[[rTokenInfo]]
denom = "uratom"
endpointList = ["https://test-cosmos-rpc1.stafihub.io:443"]
maxCommission = "0.1"
maxMissedBlocks = 100
